# Default values for p5g.

# Nodes where to place EPC Control and Payload nodes (MME, SGW, PGW)
# Nodes have to be labeled with the label indicated by epcNodeLabel and with the value in epcGroups[name].\
# Eg. for a redundant system the first node would be labeled with epcGroup: a and the second with epcGroup: b.
# Pods for mme, sgw and pgw will be deployed to these nodes.

epcNodeLabel: epcGroup

epcGroups:
  - name: "a"
    mmeCode: 1
  - name: "b"
    mmeCode: 2

# ueSettings determine how UE traffic is terminated. There are two modes; "node" or "pod". If "node" is selected
# the UE payload will be NATed using the node IP as the source. If "pod" is selected, the UE traffic will be
# NATed using the pgw POD IP as the source and the UE DNS will be the k8s DNS server.
# Note: in the case uePayloadTermination is set to node, the pgw will be greated as a privileged container.
# Note: in the case uePayloadTermination is set to pod, the pgw will need to have spec.securityContext.sysctls
# set to enable forwarding. In kubernetes 1.18 there is a bug preventing this from working.
ueSettings:
  uePayloadTermination: node # node or pod
  ueDns:                     # only needed when uePayloadTermination=node if uePayloadTermination=pod then the k8s DNS service will be used
    - 8.8.8.8
    - 8.8.4.4

# Common configuration for all mme's.
mmeConfig:
  gummei:
    plmnId:
      mcc: 208
      mnc: 93
    mmeGid: 2
  tai:
    plmnId:
      mcc: 208
      mnc: 93
    tac: 1
  security:
    integrityOrder: "[ EIA1, EIA2, EIA0 ]"
    cipheringOrder: "[ EEA0, EEA1, EEA2 ]"
  networkName:
    full: "p5g"
    mmeNamePrefix: "mme" # the name will be appended with "-<epcGroups.name>"

mongodb:
  hostName: "worker1"
  directory: "/mongodb-storage"

webui:
  loadBalancerIP: 192.168.1.250
  # The default user name and password is: admin, 1423
  
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

