{{- define "p5g.pcrf.diameterConfigName" -}}
{{- print (include "p5g.fullname" . ) "-pcrf-diameter" -}}
{{- end -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "p5g.pcrf.diameterConfigName" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "p5g.pcrfLabels" . | nindent 4 }}
data:
  pcrf-diameter.conf: |
      Identity = "pcrf.localdomain";
      Realm = "localdomain";
      
      TLS_Cred = "/etc/freeDiameter/pcrf.cert.pem", "/etc/freeDiameter/pcrf.key.pem";
      TLS_CA = "/etc/freeDiameter/cacert.pem";

      LoadExtension = "/usr/lib/x86_64-linux-gnu/freeDiameter/dbg_msg_dumps.fdx" : "0x8888";
      LoadExtension = "/usr/lib/x86_64-linux-gnu/freeDiameter/dict_rfc5777.fdx";
      LoadExtension = "/usr/lib/x86_64-linux-gnu/freeDiameter/dict_mip6i.fdx";
      LoadExtension = "/usr/lib/x86_64-linux-gnu/freeDiameter/dict_nasreq.fdx";
      LoadExtension = "/usr/lib/x86_64-linux-gnu/freeDiameter/dict_nas_mipv6.fdx";
      LoadExtension = "/usr/lib/x86_64-linux-gnu/freeDiameter/dict_dcca.fdx";
      LoadExtension = "/usr/lib/x86_64-linux-gnu/freeDiameter/dict_dcca_3gpp.fdx";

      {{ range .Values.epcGroups }}
      ConnectPeer = {{ include "p5g.pgw.diameterName" (dict "root" $ "name" .name) | quote }} { No_TLS; No_SCTP; };
      {{- end -}}
