{{/*
Creates the mongo database. Currently, the database is a single instance using a PV created using
a local disk as the storage. The node on which the PV will reside is provided by .Values.mongodb.hostName
and the path for the directory is given by .Values.mongdb.directory. It is assumed that the directory is
created by the administrator.
*/}}

{{- define "p5g.mongodbName" -}}
{{- (print (include "p5g.fullname" . ) "-mongodb" ) -}}
{{- end -}}

{{- define "p5g.mongodbLabels" -}}
db: mongodb
{{ include "p5g.labels" . }}
{{- end -}}

{{- define "p5g.mongodbSelectorLabels" -}}
db: mongodb
{{ include "p5g.selectorLabels" . }}
{{- end -}}

{{- define "p5g.mongodbURI" -}}
"mongodb://{{ include "p5g.mongodbName" . }}/open5gs"
{{- end -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "p5g.mongodbName" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "p5g.mongodbLabels" . | nindent 4}}
spec:
  selector:
    {{- include "p5g.mongodbSelectorLabels" . | nindent 4}}
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "p5g.mongodbName" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "p5g.mongodbLabels" . | nindent 4}}
spec:
  replicas: 1
  serviceName: {{ include "p5g.mongodbName" .  | quote}}
  selector:
    matchLabels:
      {{- include "p5g.mongodbSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "p5g.mongodbLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
          args:
#           - "--replSet=rs0"
            - "--bind_ip=0.0.0.0"
#           - "-vv"
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          ports:
            - containerPort: 27017
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 2
            failureThreshold: 1
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: {{ include "p5g.mongodb.PVCName" . | quote }}
