{{- define "p5g.mongodb.SCName" -}}
{{ print (include "p5g.fullname" . ) "-mongodb-sc" }}
{{- end -}}

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "p5g.mongodb.SCName" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    db: mongodb
    {{- include "p5g.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
# Supported policies: Delete, Retain
reclaimPolicy: Delete
